### ISSUE TITLE
"pzmaterial.h" file not found

### ISSUE THREAD

**Issue by gustavobat** [labmec/ErrorEstimation#1]
ErrorEstimation won't compile due to missing "pzmaterial.h" file, referred at:

https://github.com/labmec/ErrorEstimation/blob/cc3c53f29c507665c88c35d2ebc23d7e938f8af7/ErrorEstimation/main.cpp#L49

**Comment by thiagoquinelato** [comment]
This file was renamed to TPZMaterial.h. Please try to include it and let us know whether it works.

**Comment by gustavobat** [comment]
That did it! Cheers!
