### ISSUE TITLE
Condition won't be reached

### ISSUE THREAD

**Issue by gustavobat** [labmec/ErrorEstimation#2]
Due to IF(WIN32) condition in line 7,  ELSE(WIN32) won't work.

https://github.com/labmec/ErrorEstimation/blob/8c8f29ecef7058b2db93a2b211595909f14201e9/CMakeLists.txt#L10

**Comment by thiagoquinelato** [comment]
This is an else condition, not an else if. It's optional and does nothing
else than indicate which if clause this else is related with. We could
remove it if you prefer, but this indeed works as it is written now. What
do you want to do?

**Comment by gustavobat** [comment]
My mistake! I wasn't aware of this syntax.
Nevertheless, I personally think removing the WIN32 from the parenthesis after ELSE is a good idea, since it is not required and might mislead other users in the future as well.

**Comment by thiagoquinelato** [comment]
Please check whether pull request #4 does what you want.

**Comment by gustavobat** [comment]
It does.
I'm closing the issue now.
